env:
  global:
    - CC_TEST_REPORTER_ID=07d8b3bd4c80243c818a4894aa249a791f16223ddbf5688f639868c51e0d2761
language: scala
jdk: openjdk8
scala:
  - 2.12.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
after_script:
  - ./cc-test-reporter format-coverage --input-type cobertura ./api/target/scala-2.12/coverage-report/cobertura.xml
  - ./cc-test-reporter upload-coverage
